### ISSUE TITLE
estimated payments dissapeared

### ISSUE THREAD

**Issue by txapix** [Nelbert442/dero-golang-pool#10]
Hi:

Yesterday I had some workers mining and suddenly, all of my estimated payouts disappeared and the counters started at 0. Also, the worked hash line of one of my workers has dissapeared too. I don't understand why... in other times like now, even if my workers are offline they keep the hashes worked until now. Please Help.
I can send more details if needs.

Thanks!

**Comment by Nelbert442** [comment]
Please reach out to me in discord along which address (or at least the last 12 characters or so of your address). Counters will reset at each block found in regards to round shares submitted. If you do not have active miners then their stats will fall off until they re-connect. If you hit me up on discord, perhaps I can take a closer look at your specific scenario.

**Comment by txapix** [comment]
sent via discord in DM. Thanks!

**Comment by Nelbert442** [comment]
Pool-side code change applied, you should now see your miners as long as they have a share submitted within the given round or within the last 3 hours (an or, whichever is true).
