### ISSUE TITLE
GravitonDB not used?

### ISSUE THREAD

**Issue by mrbluecoat** [Nelbert442/dero-golang-pool#11]
Hi, great project! I noticed your README says `Utilizing Graviton for backend` but when I run `derod` it says `Initializing badger store`

![image](https://user-images.githubusercontent.com/382164/153223428-b30de830-347a-493f-aa0c-dc42f83fb4c9.png)

I also noticed https://github.com/Nelbert442/dero-golang-pool/blob/16720d6dff23141be654d41cfd6a9172f48753ab/stratum/stratum.go#L87 says `"pooldb") // TODO: Add to params in config.json file`

Do I need to add `pooldb` to `config.json` to enable the GravitonDB? Also, would I still leverage http://us-blockchain.dero.network/derod_database.tar.gz or do I need to just sync without a snapshot?

**Comment by mrbluecoat** [comment]
also, `go get github.com/deroproject/graviton/...` produces these binaries (none of which seem to be the main DB binary):

 * data_corruption_showcase
 * key_value_example
 * snapshot_example
 * stress

**Comment by Nelbert442** [comment]
derod is DERO's daemon (https://github.com/deroproject/derosuite). While it's a requirement for running a pool (whether hosted locally or remotely) and configured within as your upstream [Upstream Config](https://github.com/Nelbert442/dero-golang-pool/blob/master/config_example.json#L27) it is not related to the binaries for this project directly. You need to run derod to query the chain (fully synced) for blocks etc.

This section outlines getting the repo and building:  [Downloading-Installing](https://github.com/Nelbert442/dero-golang-pool#downloading--installing) and [Building](https://github.com/Nelbert442/dero-golang-pool#buildstart-the-pool)

**Comment by Nelbert442** [comment]
> also, `go get github.com/deroproject/graviton/...` produces these binaries (none of which seem to be the main DB binary):
> 
> * data_corruption_showcase
> * key_value_example
> * snapshot_example
> * stress

Those binaries aren't necessary for this, it's simply to get the graviton package dependencies.
