### ISSUE TITLE
Invalid Address?

### ISSUE THREAD

**Issue by dougb57** [Nelbert442/dero-golang-pool#3]
Everything seemed to be going along just fine, setup and sync of node, install of dero-golang-pool. Then when trying to log into pool with miner machine, using XMRIG, when I get this error "[Util] Address prefix (100) and pool address prefix (60) do not match. Invalid address."  , Also followed by, "Invalid address dERobhb...................7uWaPuv4 used for login by 192.168.1.103.

I get the same error from any address I try, ie generated by GUI wallet, CLI wallet, even Web wallet.

config json from pool
[config.txt](https://github.com/Nelbert442/dero-golang-pool/files/5938229/config.txt)

conrfig  XMRIG
[config.XMRIG.txt](https://github.com/Nelbert442/dero-golang-pool/files/5938231/config.XMRIG.txt)

**Comment by dougb57** [comment]
using Ubuntu 19.10
go version go1.15.8 linux/amd64
xmrig 6.7.2

**Comment by xmrminers** [comment]
Pool config is all wrong, address is the wallet address of the pool and pool host is the ip or hostname pointing at the pool.

**Comment by Nelbert442** [comment]
Agreed with xmrminers, pls check Readme for descriptions of each item in pool config and re-check against the config_example.json file.

**Comment by dougb57** [comment]
Many thanks! It's working now,
