### ISSUE TITLE
Web Page for Pool question

### ISSUE THREAD

**Issue by dougb57** [Nelbert442/dero-golang-pool#4]
Just was wondering if the Web Page is supposed to automatically populate, or  if not, what needs to be done to bring it up online? 
The frames are there , but no data.

**Comment by Nelbert442** [comment]
Be sure your config.js file for the site has the api url match what you're using for api. https://github.com/Nelbert442/dero-golang-pool#host-the-api

**Comment by Nelbert442** [comment]
Added some more tidbits to the README describing modifying config.js to match the api url you define in config.json for the pool. Closing issue.

**Comment by dougb57** [comment]
thank you

    On Tuesday, February 9, 2021, 12:10:09 PM CST, Nelbert442 <notifications@github.com> wrote:  
 
 


Added some more tidbits to the README describing modifying config.js to match the api url you define in config.json for the pool. Closing issue.
