### ISSUE TITLE
No data problem

### ISSUE THREAD

**Issue by bzhubs** [Nelbert442/dero-golang-pool#5]
Hello, I deployed it normally, and it can be opened normally, but no data can be obtained

![image](https://user-images.githubusercontent.com/28048361/109976772-1c83b900-7d37-11eb-95b7-e8abd2b37c91.png)
![image](https://user-images.githubusercontent.com/28048361/109976915-3b824b00-7d37-11eb-9e2c-e0d42a72af0d.png)
![image](https://user-images.githubusercontent.com/28048361/109976961-45a44980-7d37-11eb-96ef-cbc9ec9d5153.png)

config.json
{
        "poolHost": "dero.mydomain.com",
        "blockchainExplorer": "https://explorer.dero.io/block/{id}",
        "transactionExplorer": "https://explorer.dero.io/tx/{id}",
        "address": "dERooRjvDh6FXVLDGw8bkcWJkuYb7ZnZGB4CgynBymTgXZwRbwanWNPhgySnVNb6MjY5uAjZNoimmRzjvpuruPDp6eyPsdbKBr",
        "donationAddress": "dERooRjvDh6FXVLDGw8bkcWJkuYb7ZnZGB4CgynBymTgXZwRbwanWNPhgySnVNb6MjY5uAjZNoimmRzjvpuruPDp6eyPsdbKBr",
        "donationDescription": "Thank you for supporting our mining pool!",
        "bypassShareValidation": false,

        "threads": 2,
        "algo": "astrobwt",
        "coin": "DERO",
        "coinUnits": 1000000000000,
        "coinDecimalPlaces": 4,
        "coinDifficultyTarget": 27,

        "trustedSharesCount": 30,
        "blockRefreshInterval": "120ms",
        "hashrateExpiration": "3h",
        "storeMinerStatsInterval": "5s",

        "gravitonMaxSnapshots": 5000,
        "gravitonMigrateWait": "100ms",

        "upstreamCheckInterval": "5s",

        "upstream": [
                {
                        "enabled": true,
                        "name": "Derod",
                        "host": "127.0.0.1",
                        "port": 20206,
                        "timeout": "10s"
                },
                {
                        "enabled": false,
                        "name": "Remote Derod",
                        "host": "derodaemon.nelbert442.com",
                        "port": 20206,
                        "timeout": "10s"
                }
        ],

        "stratum": {
                "paymentId": {
                        "addressSeparator": "+"
                },
                "fixedDiff": {
                        "addressSeparator": "."
                },
                "workerID": {
                        "addressSeparator": "@"
                },
                "donatePercent": {
                        "addressSeparator": "%"
                },
                "soloMining": {
                        "enabled": true,
                        "addressSeparator": "~"
                },

                "timeout": "15m",
                "healthCheck": true,
                "maxFails": 100,

                "listen": [
                        {
                                "host": "0.0.0.0",
                                "port": 1111,
                                "diff": 1000,
                                "minDiff": 500,
                                "maxConn": 32768,
                                "desc": "Low end hardware"
                        },
                        {
                                "host": "0.0.0.0",
                                "port": 3333,
                                "diff": 2500,
                                "minDiff": 500,
                                "maxConn": 32768,
                                "desc": "Mid range hardware"
                        },
                        {
                                "host": "0.0.0.0",
                                "port": 5555,
                                "diff": 5000,
                                "minDiff": 500,
                                "maxConn": 32768,
                                "desc": "High end hardware"
                        }
                ],

                "varDiff": {
                        "enabled": true,
                        "minDiff": 750,
                        "maxDiff": 1000000,
                        "targetTime": 20,
                        "retargetTime": 120,
                        "variancePercent": 30,
                        "maxJump": 50
                }
        },

        "api": {
                "enabled": true,
                "listen": "0.0.0.0:8082",
                "statsCollectInterval": "5s",
                "hashrateWindow": "10m",
                "payments": 30,
                "blocks": 50,
                "ssl": false,
                "sslListen": "0.0.0.0:9092",
                "certFile": "fullchain.cer",
                "keyFile": "cert.key"
        },

        "unlocker": {
                "enabled": true,
                "poolFee": 0.1,
                "depth": 60,
                "interval": "5m"
        },

        "payments": {
                "enabled": true,
                "interval": "5m",
                "mixin": 8,
                "maxAddresses": 2,
                "minPayment": 10000000000,
                "walletHost": "127.0.0.1",
                "walletPort": "20202"
        },

        "website": {
                "enabled": true,
                "port": "80",
                "ssl": false,
                "sslPort": "9090",
                "certFile": "fullchain.cer",
                "keyFile": "cert.key"
        },

        "poolcharts": {
                "interval": 60,
                "hashrate": {
                        "enabled": true,
                        "maximumPeriod": 86400
                },
                "miners": {
                        "enabled": true,
                        "maximumPeriod": 86400
                },
                "workers": {
                        "enabled": true,
                        "maximumPeriod": 86400
                },
                "difficulty": {
                        "enabled": true,
                        "maximumPeriod": 86400
                }
        }
}

**Comment by Nelbert442** [comment]
Be sure that your website config.js file points api to your configured api endpoint:

    "api": {
            "enabled": true,
            "listen": "0.0.0.0:8082",
            "statsCollectInterval": "5s",
            "hashrateWindow": "10m",
            "payments": 30,
            "blocks": 50,
            "ssl": false,
            "sslListen": "0.0.0.0:9092",
            "certFile": "fullchain.cer",
            "keyFile": "cert.key"
    },
    
    This is listening on 0.0.0.0 (local to the machine that is running the pool). Ensure that your frontend config.js file points api over to the IP and port as defined here. This is how data flows: https://github.com/Nelbert442/dero-golang-pool/blob/master/website/site/config.js

**Comment by bzhubs** [comment]
cat config.js 
var api = "http://127.0.0.1:8082/api";
var discord = "https://discord.gg/H95TJDp";

Please help me, thank you very much!

**Comment by Nelbert442** [comment]
If you hit F12 you should see network errors that are most likely pointing to not being able to reach the api, perhaps look at that. 

Also, of course, ensure that the daemon is running on your pool , since you're configured for 127.0.0.1:20206, or you can test by just setting your local to false and then the remote node I have pre-populated to my daemons to true:

```
"upstream": [
            {
                    "enabled": true,
                    "name": "Derod",
                    "host": "127.0.0.1",
                    "port": 20206,
                    "timeout": "10s"
            },
            {
                    "enabled": false,
                    "name": "Remote Derod",
                    "host": "derodaemon.nelbert442.com",
                    "port": 20206,
                    "timeout": "10s"
            }
    ],
```

**Comment by bzhubs** [comment]
Thank you, it turned out to be an API problem, so I changed 127.0.0.1 to the public IP problem and solved it

**Comment by bzhubs** [comment]
{
                    "enabled": false,
                    "name": "Remote Derod",
                    "host": "derodaemon.nelbert442.com",
                    "port": 20206,
                    "timeout": "10s"
            }

What does this mean?    "host": "derodaemon.nelbert442.com",  and "name": "Remote Derod",

**Comment by bzhubs** [comment]
Thank you，I have understood.

**Comment by Nelbert442** [comment]
The "upstream"s are the DERO Daemons that are required to be running. If you don't have a daemon running, you won't be able to mine to the network/blocks etc. The upstreams is a list of , in priority order , daemons that are utilized. If upstream[0] (the first instance) is unavailable, the pool fails over to upstream[1] and so on. All that second one is there for is more ease of use for anyone running the pool. I host public nodes for DERO that are behind derodaemon.nelbert442.com:20206 that you're more than welcome to use.

I recommend , of course, utilizing your own DERO node for the pool for latency + own your own stack configurations, however it is there for a failover option in the event your daemon has a failure or something along those lines to keep your pool up and running.

**Comment by bzhubs** [comment]
That is to achieve high availability，very good.

**Comment by Nelbert442** [comment]
Yep , absolutely :)

**Comment by bzhubs** [comment]
Excellent developers, consider all the problems

**Comment by Nelbert442** [comment]
Much appreciated :) I welcome any feedback/recommendations. I have many future plans that will expand the high availability of the pool, as time allows it. So I hope for some good future updates that will assist all who utilize my pool & pool repo :)

**Comment by bzhubs** [comment]
![image](https://user-images.githubusercontent.com/28048361/109980186-98333500-7d3a-11eb-9db7-4fad57707ddf.png)

 have data, thank you again for your technical support.

**Comment by Nelbert442** [comment]
My pleasure! If you have any other questions/concerns. Feel free to reach out, no issues at all and will do my best to assist.

**Comment by bzhubs** [comment]
Thank you, have a pleasant workday.

**Comment by Nelbert442** [comment]
You as well. Closing the issue, thanks.
