### ISSUE TITLE
High availability problem

### ISSUE THREAD

**Issue by bzhubs** [Nelbert442/dero-golang-pool#6]
Hello, suppose I use 3 servers to build a cluster environment. 192.168.1.10 for nginx tcp proxy, 192.168.1.11 and 192.168.1.12 pool, how should I configure the congfig.json file, will there be a problem with the pooldb file?

The user connects to the 192.168.1.10 server, the server will automatically select any server 192.168.1.11, 192.168.1.12

192.168.1.13 is dero wallet

nginx tcp proxy: 192.168.1.10
pool1: 192.168.1.11
pool2: 192.168.1.12
dero wallet:  192.168.1.13

pool1 and pool2 config.json

{
        "poolHost": "pool.mydomain.com",
        "blockchainExplorer": "https://explorer.dero.io/block/{id}",
        "transactionExplorer": "https://explorer.dero.io/tx/{id}",
        "address": "dERooRjvDh6FXVLDGw8bkcWJkuYb7ZnZGB4CgynBymTgXZwRbwanWNPhgySnVNb6MjY5uAjZNoimmRzjvpuruPDp6eyPsdbKBr",
        "donationAddress": "dERooRjvDh6FXVLDGw8bkcWJkuYb7ZnZGB4CgynBymTgXZwRbwanWNPhgySnVNb6MjY5uAjZNoimmRzjvpuruPDp6eyPsdbKBr",
        "donationDescription": "Thank you for supporting our mining pool!",
        "bypassShareValidation": false,

        "threads": 2,
        "algo": "astrobwt",
        "coin": "DERO",
        "coinUnits": 1000000000000,
        "coinDecimalPlaces": 4,
        "coinDifficultyTarget": 27,

        "trustedSharesCount": 30,
        "blockRefreshInterval": "120ms",
        "hashrateExpiration": "3h",
        "storeMinerStatsInterval": "5s",

        "gravitonMaxSnapshots": 5000,
        "gravitonMigrateWait": "100ms",

        "upstreamCheckInterval": "5s",

        "upstream": [
                {
                        "enabled": true,
                        "name": "Derod",
                        "host": "192.168.1.13",
                        "port": 20206,
                        "timeout": "10s"
                }\
        ],

        "stratum": {
                "paymentId": {
                        "addressSeparator": "+"
                },
                "fixedDiff": {
                        "addressSeparator": "."
                },
                "workerID": {
                        "addressSeparator": "@"
                },
                "donatePercent": {
                        "addressSeparator": "%"
                },
                "soloMining": {
                        "enabled": true,
                        "addressSeparator": "~"
                },

                "timeout": "15m",
                "healthCheck": true,
                "maxFails": 100,

                "listen": [
                        {
                                "host": "0.0.0.0",
                                "port": 1111,
                                "diff": 1000,
                                "minDiff": 500,
                                "maxConn": 32768,
                                "desc": "Low end hardware"
                        },
                        {
                                "host": "0.0.0.0",
                                "port": 3333,
                                "diff": 2500,
                                "minDiff": 500,
                                "maxConn": 32768,
                                "desc": "Mid range hardware"
                        },
                        {
                                "host": "0.0.0.0",
                                "port": 5555,
                                "diff": 5000,
                                "minDiff": 500,
                                "maxConn": 32768,
                                "desc": "High end hardware"
                        }
                ],

                "varDiff": {
                        "enabled": true,
                        "minDiff": 750,
                        "maxDiff": 1000000,
                        "targetTime": 20,
                        "retargetTime": 120,
                        "variancePercent": 30,
                        "maxJump": 50
                }
        },

        "api": {
                "enabled": true,
                "listen": "0.0.0.0:8082",
                "statsCollectInterval": "5s",
                "hashrateWindow": "10m",
                "payments": 30,
                "blocks": 50,
                "ssl": false,
                "sslListen": "0.0.0.0:9092",
                "certFile": "fullchain.cer",
                "keyFile": "cert.key"
        },

        "unlocker": {
                "enabled": true,
                "poolFee": 0.8,
                "depth": 60,
                "interval": "5m"
        },

        "payments": {
                "enabled": true,
                "interval": "5m",
                "mixin": 8,
                "maxAddresses": 2,
                "minPayment": 10000000000,
                "walletHost": "192.168.1.13",
                "walletPort": "20202"
        },

        "website": {
                "enabled": true,
                "port": "80",
                "ssl": false,
                "sslPort": "9090",
                "certFile": "fullchain.cer",
                "keyFile": "cert.key"
        },

        "poolcharts": {
                "interval": 60,
                "hashrate": {
                        "enabled": true,
                        "maximumPeriod": 86400
                },
                "miners": {
                        "enabled": true,
                        "maximumPeriod": 86400
                },
                "workers": {
                        "enabled": true,
                        "maximumPeriod": 86400
                },
                "difficulty": {
                        "enabled": true,
                        "maximumPeriod": 86400
                }
        }
}

**Comment by Nelbert442** [comment]
There is not currently support for multiple pool instances running routing to a single frontend.

This is a future item that is planned, but not yet implemented.  DB sync between nodes is not yet implemented.

**Comment by bzhubs** [comment]
ok,Thank you.
